version: '3'

services:
  product_backend:
    build: ./ecom
    command:  bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: product_api
    volumes:
      - ./ecom:/app
    ports:
      - "8000:8000"


  product_db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data: